"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import Myclass

# Implementing MyFrame1
class MyProject1MyFrame1( Myclass.MyFrame1 ):
	def __init__( self, parent ):
		Myclass.MyFrame1.__init__( self, parent )

	# Handlers for MyFrame1 events.
	def CalcNumber( self, event ):
		# TODO: Implement CalcNumber
		QBit = int(self.m_comboBox1.GetValue())
		Val = float(self.m_textCtrl2.GetValue())

		Numf = 0
		f, d = math.modf(Val)
		for i in range(QBit):
			f, s = math.modf(f * 2)
			Numf += s * 2 ** (QBit - i -1)

		Numd = d * 2 ** (QBit)
		self.Num = int(Numd + Numf)

		# if Sign:
		# 	Num = ~Num + 1

		# self.m_textCtrl3.SetValue('{:.0f}'.format(Num))
		self.m_textCtrl3.SetValue(str(self.Num))
		pass

	def Clipboard( self, event ):
		# TODO: Implement Clipboard
		pass


"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import Myclass
import math
import pyperclip

# Implementing MyFrame1
class MyProject1MyFrame1( Myclass.MyFrame1 ):
	def __init__( self, parent ):
		Myclass.MyFrame1.__init__( self, parent )
		self.Num = self.m_textCtrl3.GetValue()

	# Handlers for MyFrame1 events.
	def CalcNumber( self, event ):
		# TODO: Implement CalcNumber
		QBit = int(self.m_comboBox1.GetValue())
		Val = float(self.m_textCtrl2.GetValue())
		FPNVal = float(self.m_textCtrl31.GetValue())

		Numf = 0
		f, d = math.modf(Val)
		for i in range(QBit):
			f, s = math.modf(f * 2)
			Numf += s * 2 ** (QBit - i -1)

		Numd = d * 2 ** (QBit)
		self.Num = int(Numd + Numf)

		# if Sign:
		# 	Num = ~Num + 1

		# self.m_textCtrl3.SetValue('{:.0f}'.format(Num))
		self.m_textCtrl3.SetValue(str(self.Num))
		self.m_textCtrl4.SetValue(str(FPNVal / (2 ** QBit)))
		pass

	def Clipboard( self, event ):
		# TODO: Implement Clipboard
		pyperclip.copy(str(self.Num))
		pass


